application:
  local-ip: localhost

spring:
  datasource:
    url: jdbc:mysql:\\${local-ip}:3306\quizxquiz
    username: root
    password: thisisnotasecurepassword
  jpa:
    hibernate:
      ddl-auto: update